### ISSUE TITLE
incorrect rslurm info in VS table

### ISSUE THREAD

**Issue by reblake** [USCbiostats/slurmR#22] opened 2019-10-30 16:15 UTC
1) rslurm package has always been active, and is currently active to present
2) rslurm::slurm_apply() provides functionality similar to the apply family in base R, so table should read "yes"

**Comment by gvegayon** [comment] 2019-10-31 23:09
I can see that the package is on active development now. I will change that! Regarding the second point, I don't agree. The `rslurm::slurm_apply` does not receive either a list or a vector as argument. It is somewhat similar to `apply` with the difference that `apply` is made for arrays, not data.frames. `slurmR` has `Slurm_lapply`, `Slurm_sapply`, and `Slurm_Map` which are analogous to their pairs `lapply`, `sapply`, and `Map` from base R. This is also true for the `batchtools` package which has `btlapply` and `btmapply`.

**Comment by gvegayon** [comment] 2019-10-31 23:39
fixed on f4894dce67a11259cd983a50708b0bf3d437951d

**Comment by qdread** [comment] 2020-02-13 20:13
Hi, I would like to follow up on this issue. `rslurm::slurm_apply` was intended from the beginning to be analogous to `mapply` in base R, and in our development version on GitHub we also have a function `slurm_map` that is analogous to `lapply` in base R or `purrr::map`. The syntax of both was designed to match their base R counterparts. Therefore I think it's appropriate to say "yes" for the 2nd column entry for the rslurm package in the comparison table. Thanks!

**Comment by gvegayon** [comment] 2020-02-13 21:20
WIll change it asap :). Thanks for the update!

**Comment by qdread** [comment] 2020-02-14 00:05
Thanks!!!

**Closed** 2020-02-14 20:19 UTC
